---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# dauwrs

This repository contains the data and code for our paper:

> Hayes, Elspeth, Richard Fullagar, Ben Marwick (2018). _Database of Australian Usewear/Residue Studies, Artefact Design and Multi-purpose Tools_.  <https://doi.org/x10.17605/OSF.IO/MYBG2>

Our pre-print is online here:

> Authors, (2018). _Title of paper_. Name of journal/book, Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/10.13140/RG.2.2.24109.95204>


### How to cite

Please cite this compendium as:

> Hayes, Elspeth, Richard Fullagar, Ben Marwick, (`r format(Sys.Date(), "%Y")`). _Compendium of R code and data for '_Database of Australian Usewear/Residue Studies, Artefact Design and Multi-purpose Tools_'_. Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/10.17605/OSF.IO/MYBG2>

### How to download or install

You can download the compendium as a zip from from this URL: [/archive/master.zip](archive/master.zip)


### Licenses

**Text and figures :**  [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)

**Code :** See the [DESCRIPTION](DESCRIPTION) file

**Data :** [CC-0](http://creativecommons.org/publicdomain/zero/1.0/) attribution requested in reuse

### Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.md). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.

